# Generated by Django 4.1 on 2022-08-22 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("helper", "0002_rename_user_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistiveAids",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("vendor", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="disabilityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disability_type",
                    models.CharField(
                        choices=[("1", "Blindness"), ("2", "Deaf")],
                        default="1",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "disability_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helper.disabilitytype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schemes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=200)),
                ("disability_benefits_criteria", models.IntegerField()),
                ("benefit_types", models.CharField(max_length=500)),
                ("document", models.URLField()),
                ("summary", models.CharField(max_length=500)),
                (
                    "disability_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helper.disabilitytype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("phone", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(name="Profile",),
        migrations.AddField(
            model_name="assistiveaids",
            name="disability_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="helper.disabilitytype"
            ),
        ),
    ]
