# Generated by Django 4.1 on 2022-08-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helper", "0003_assistiveaids_disabilitytype_profileuser_schemes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaregiverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("middle_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("address_line_1", models.CharField(max_length=150)),
                ("address_line_2", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("pin_code", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="schemes", old_name="document", new_name="document_link",
        ),
        migrations.RemoveField(model_name="profileuser", name="address",),
        migrations.RemoveField(model_name="profileuser", name="name",),
        migrations.RemoveField(model_name="volunteerprofile", name="location",),
        migrations.RemoveField(model_name="volunteerprofile", name="name",),
        migrations.AddField(
            model_name="profileuser",
            name="address_line_1",
            field=models.CharField(default=" ", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="address_line_2",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="city",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="first_name",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="last_name",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="middle_name",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="password",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="pin_code",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="state",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="udid",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schemes",
            name="highlights",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schemes",
            name="scheme_name",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="address_line_1",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="address_line_2",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="city",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="first_name",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="last_name",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="middle_name",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="pin_code",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="state",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schemes",
            name="benefit_types",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="schemes",
            name="disability_benefits_criteria",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="schemes", name="state", field=models.CharField(max_length=50),
        ),
    ]
