# Generated by Django 4.1 on 2022-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helper", "0004_caregiverprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="disability_type",
            field=models.CharField(
                choices=[("1", "Blindness"), ("2", "Deaf")], default="1", max_length=20
            ),
        ),
    ]
