# Generated by Django 4.1 on 2022-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helper", "0005_alter_profileuser_disability_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileuser",
            name="disability_type",
            field=models.CharField(
                choices=[
                    ("1", "Hearing Impairment"),
                    ("2", "Autism"),
                    ("3", "Leprosy"),
                    ("4", "Intellectual Disability"),
                    ("5", "Complete Blindness"),
                    ("6", "Person With Low Vision"),
                    ("7", "Handicapped"),
                    ("8", "Dyslexia"),
                    ("9", "Cerebral Palsy"),
                    ("10", "Locomotor Disability"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="schemes",
            name="disability_type",
            field=models.CharField(
                choices=[
                    ("1", "Hearing Impairment"),
                    ("2", "Autism"),
                    ("3", "Leprosy"),
                    ("4", "Intellectual Disability"),
                    ("5", "Complete Blindness"),
                    ("6", "Person With Low Vision"),
                    ("7", "Handicapped"),
                    ("8", "Dyslexia"),
                    ("9", "Cerebral Palsy"),
                    ("10", "Locomotor Disability"),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
