# Generated by Django 4.1 on 2022-08-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helper", "0006_alter_profileuser_disability_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="CaregiverProfile",),
        migrations.AddField(
            model_name="profileuser",
            name="caregiver_email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="caregiver_first_name",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="caregiver_last_name",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="caregiver_middle_name",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profileuser",
            name="caregiver_phone",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assistiveaids",
            name="disability_type",
            field=models.CharField(
                choices=[
                    ("1", "Hearing Impairment"),
                    ("2", "Autism"),
                    ("3", "Leprosy"),
                    ("4", "Intellectual Disability"),
                    ("5", "Complete Blindness"),
                    ("6", "Person With Low Vision"),
                    ("7", "Handicapped"),
                    ("8", "Dyslexia"),
                    ("9", "Cerebral Palsy"),
                    ("10", "Locomotor Disability"),
                ],
                default="1",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(name="disabilityType",),
    ]
