# Generated by Django 4.0.3 on 2022-08-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_delete_caregiverprofile_profileuser_caregiver_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='highlights',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
