# Generated by Django 4.0.3 on 2022-08-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_alter_schemes_highlights_alter_schemes_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='caregiver_middle_name',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='aadhar_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
