# Generated by Django 4.0.3 on 2022-08-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_volunteerprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='phone',
        ),
    ]
