# Generated by Django 4.0.3 on 2022-08-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0011_remove_volunteerprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='address_line_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='name',
            field=models.CharField(default='Rahul', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='caregiver_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='caregiver_first_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='caregiver_last_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='caregiver_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
