# Generated by Django 4.0.3 on 2022-08-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0012_rename_address_line_1_profileuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='caregiver_email',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='caregiver_first_name',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='caregiver_last_name',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='caregiver_phone',
        ),
    ]
